<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6HGP4Q4" ignored="0" name="BiometricsLoginV2" tests="4" failures="1" timestamp="19 Mar 2020 10:22:30 GMT" time="0.706" errors="0">
  <testcase name="invalidUsernameValidfingerPrintAndFingerCode" time="0.152" classname="services.BiometricsLoginV2"/>
  <testcase name="validUsernameInvalidfingerPrintAndValidFingerCode" time="0.076" classname="services.BiometricsLoginV2">
    <failure type="java.lang.AssertionError" message="expected [419] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [419] but found [0]
at services.BiometricsLoginV2.biometricLoginBase(BiometricsLoginV2.java:64)
at services.BiometricsLoginV2.validUsernameInvalidfingerPrintAndValidFingerCode(BiometricsLoginV2.java:99)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validUsernameInvalidfingerPrintAndValidFingerCode -->
  <testcase name="validUsernameValidfingerPrintAndFingerCode" time="0.071" classname="services.BiometricsLoginV2"/>
  <testcase name="validUsernameValidfingerPrintAndInvalidFingerCode" time="0.065" classname="services.BiometricsLoginV2"/>
</testsuite> <!-- BiometricsLoginV2 -->
